#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepcaoDados
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RecepcaoSistema")]
	public partial class RecepcaoDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFuncionario(Funcionario instance);
    partial void UpdateFuncionario(Funcionario instance);
    partial void DeleteFuncionario(Funcionario instance);
    partial void InsertVisitante(Visitante instance);
    partial void UpdateVisitante(Visitante instance);
    partial void DeleteVisitante(Visitante instance);
    partial void InsertVisita(Visita instance);
    partial void UpdateVisita(Visita instance);
    partial void DeleteVisita(Visita instance);
    partial void InsertSecretaria(Secretaria instance);
    partial void UpdateSecretaria(Secretaria instance);
    partial void DeleteSecretaria(Secretaria instance);
    #endregion
		
		public RecepcaoDataClassesDataContext() : 
				base(global::RecepcaoDados.Properties.Settings.Default.RecepcaoSistemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionario
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
		
		public System.Data.Linq.Table<Visitante> Visitante
		{
			get
			{
				return this.GetTable<Visitante>();
			}
		}
		
		public System.Data.Linq.Table<Visita> Visita
		{
			get
			{
				return this.GetTable<Visita>();
			}
		}
		
		public System.Data.Linq.Table<Secretaria> Secretaria
		{
			get
			{
				return this.GetTable<Secretaria>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcionario")]
	public partial class Funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFuncionario;
		
		private string _Nome;
		
		private string _Login;
		
		private string _Senha;
		
		private string _Perfil;
		
		private EntitySet<Visita> _Visita;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFuncionarioChanging(int value);
    partial void OnIdFuncionarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnPerfilChanging(string value);
    partial void OnPerfilChanged();
    #endregion
		
		public Funcionario()
		{
			this._Visita = new EntitySet<Visita>(new Action<Visita>(this.attach_Visita), new Action<Visita>(this.detach_Visita));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFuncionario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFuncionario
		{
			get
			{
				return this._IdFuncionario;
			}
			set
			{
				if ((this._IdFuncionario != value))
				{
					this.OnIdFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._IdFuncionario = value;
					this.SendPropertyChanged("IdFuncionario");
					this.OnIdFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perfil", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Perfil
		{
			get
			{
				return this._Perfil;
			}
			set
			{
				if ((this._Perfil != value))
				{
					this.OnPerfilChanging(value);
					this.SendPropertyChanging();
					this._Perfil = value;
					this.SendPropertyChanged("Perfil");
					this.OnPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcionario_Visita", Storage="_Visita", ThisKey="IdFuncionario", OtherKey="IdFuncionario")]
		public EntitySet<Visita> Visita
		{
			get
			{
				return this._Visita;
			}
			set
			{
				this._Visita.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Funcionario = this;
		}
		
		private void detach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Funcionario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visitante")]
	public partial class Visitante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVisitante;
		
		private string _CPF;
		
		private string _RG;
		
		private string _RNE;
		
		private string _Nome;
		
		private System.Nullable<bool> _Estrangeiro;
		
		private System.Nullable<byte> _Idade;
		
		private string _Logradouro;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _Pais;
		
		private string _Foto;
		
		private EntitySet<Visita> _Visita;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVisitanteChanging(int value);
    partial void OnIdVisitanteChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnRNEChanging(string value);
    partial void OnRNEChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEstrangeiroChanging(System.Nullable<bool> value);
    partial void OnEstrangeiroChanged();
    partial void OnIdadeChanging(System.Nullable<byte> value);
    partial void OnIdadeChanged();
    partial void OnLogradouroChanging(string value);
    partial void OnLogradouroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnFotoChanging(string value);
    partial void OnFotoChanged();
    #endregion
		
		public Visitante()
		{
			this._Visita = new EntitySet<Visita>(new Action<Visita>(this.attach_Visita), new Action<Visita>(this.detach_Visita));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVisitante", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVisitante
		{
			get
			{
				return this._IdVisitante;
			}
			set
			{
				if ((this._IdVisitante != value))
				{
					this.OnIdVisitanteChanging(value);
					this.SendPropertyChanging();
					this._IdVisitante = value;
					this.SendPropertyChanged("IdVisitante");
					this.OnIdVisitanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(15)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(15)")]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNE", DbType="VarChar(15)")]
		public string RNE
		{
			get
			{
				return this._RNE;
			}
			set
			{
				if ((this._RNE != value))
				{
					this.OnRNEChanging(value);
					this.SendPropertyChanging();
					this._RNE = value;
					this.SendPropertyChanged("RNE");
					this.OnRNEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estrangeiro", DbType="Bit")]
		public System.Nullable<bool> Estrangeiro
		{
			get
			{
				return this._Estrangeiro;
			}
			set
			{
				if ((this._Estrangeiro != value))
				{
					this.OnEstrangeiroChanging(value);
					this.SendPropertyChanging();
					this._Estrangeiro = value;
					this.SendPropertyChanged("Estrangeiro");
					this.OnEstrangeiroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idade", DbType="TinyInt")]
		public System.Nullable<byte> Idade
		{
			get
			{
				return this._Idade;
			}
			set
			{
				if ((this._Idade != value))
				{
					this.OnIdadeChanging(value);
					this.SendPropertyChanging();
					this._Idade = value;
					this.SendPropertyChanged("Idade");
					this.OnIdadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logradouro", DbType="VarChar(50)")]
		public string Logradouro
		{
			get
			{
				return this._Logradouro;
			}
			set
			{
				if ((this._Logradouro != value))
				{
					this.OnLogradouroChanging(value);
					this.SendPropertyChanging();
					this._Logradouro = value;
					this.SendPropertyChanged("Logradouro");
					this.OnLogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50)")]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(50)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarChar(50)")]
		public string Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visitante_Visita", Storage="_Visita", ThisKey="IdVisitante", OtherKey="IdVisitante")]
		public EntitySet<Visita> Visita
		{
			get
			{
				return this._Visita;
			}
			set
			{
				this._Visita.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Visitante = this;
		}
		
		private void detach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Visitante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visita")]
	public partial class Visita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVisita;
		
		private int _IdVisitante;
		
		private int _IdFuncionario;
		
		private string _Secretaria;
		
		private string _Setor;
		
		private string _ContatoInterno;
		
		private bool _Liberacao;
		
		private System.DateTime _Data;
		
		private EntityRef<Funcionario> _Funcionario;
		
		private EntityRef<Visitante> _Visitante;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVisitaChanging(int value);
    partial void OnIdVisitaChanged();
    partial void OnIdVisitanteChanging(int value);
    partial void OnIdVisitanteChanged();
    partial void OnIdFuncionarioChanging(int value);
    partial void OnIdFuncionarioChanged();
    partial void OnSecretariaChanging(string value);
    partial void OnSecretariaChanged();
    partial void OnSetorChanging(string value);
    partial void OnSetorChanged();
    partial void OnContatoInternoChanging(string value);
    partial void OnContatoInternoChanged();
    partial void OnLiberacaoChanging(bool value);
    partial void OnLiberacaoChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    #endregion
		
		public Visita()
		{
			this._Funcionario = default(EntityRef<Funcionario>);
			this._Visitante = default(EntityRef<Visitante>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVisita", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVisita
		{
			get
			{
				return this._IdVisita;
			}
			set
			{
				if ((this._IdVisita != value))
				{
					this.OnIdVisitaChanging(value);
					this.SendPropertyChanging();
					this._IdVisita = value;
					this.SendPropertyChanged("IdVisita");
					this.OnIdVisitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVisitante", DbType="Int NOT NULL")]
		public int IdVisitante
		{
			get
			{
				return this._IdVisitante;
			}
			set
			{
				if ((this._IdVisitante != value))
				{
					if (this._Visitante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVisitanteChanging(value);
					this.SendPropertyChanging();
					this._IdVisitante = value;
					this.SendPropertyChanged("IdVisitante");
					this.OnIdVisitanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFuncionario", DbType="Int NOT NULL")]
		public int IdFuncionario
		{
			get
			{
				return this._IdFuncionario;
			}
			set
			{
				if ((this._IdFuncionario != value))
				{
					if (this._Funcionario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._IdFuncionario = value;
					this.SendPropertyChanged("IdFuncionario");
					this.OnIdFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secretaria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Secretaria
		{
			get
			{
				return this._Secretaria;
			}
			set
			{
				if ((this._Secretaria != value))
				{
					this.OnSecretariaChanging(value);
					this.SendPropertyChanging();
					this._Secretaria = value;
					this.SendPropertyChanged("Secretaria");
					this.OnSecretariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Setor
		{
			get
			{
				return this._Setor;
			}
			set
			{
				if ((this._Setor != value))
				{
					this.OnSetorChanging(value);
					this.SendPropertyChanging();
					this._Setor = value;
					this.SendPropertyChanged("Setor");
					this.OnSetorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContatoInterno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContatoInterno
		{
			get
			{
				return this._ContatoInterno;
			}
			set
			{
				if ((this._ContatoInterno != value))
				{
					this.OnContatoInternoChanging(value);
					this.SendPropertyChanging();
					this._ContatoInterno = value;
					this.SendPropertyChanged("ContatoInterno");
					this.OnContatoInternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liberacao", DbType="Bit NOT NULL")]
		public bool Liberacao
		{
			get
			{
				return this._Liberacao;
			}
			set
			{
				if ((this._Liberacao != value))
				{
					this.OnLiberacaoChanging(value);
					this.SendPropertyChanging();
					this._Liberacao = value;
					this.SendPropertyChanged("Liberacao");
					this.OnLiberacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcionario_Visita", Storage="_Funcionario", ThisKey="IdFuncionario", OtherKey="IdFuncionario", IsForeignKey=true)]
		public Funcionario Funcionario
		{
			get
			{
				return this._Funcionario.Entity;
			}
			set
			{
				Funcionario previousValue = this._Funcionario.Entity;
				if (((previousValue != value) 
							|| (this._Funcionario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Funcionario.Entity = null;
						previousValue.Visita.Remove(this);
					}
					this._Funcionario.Entity = value;
					if ((value != null))
					{
						value.Visita.Add(this);
						this._IdFuncionario = value.IdFuncionario;
					}
					else
					{
						this._IdFuncionario = default(int);
					}
					this.SendPropertyChanged("Funcionario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visitante_Visita", Storage="_Visitante", ThisKey="IdVisitante", OtherKey="IdVisitante", IsForeignKey=true)]
		public Visitante Visitante
		{
			get
			{
				return this._Visitante.Entity;
			}
			set
			{
				Visitante previousValue = this._Visitante.Entity;
				if (((previousValue != value) 
							|| (this._Visitante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Visitante.Entity = null;
						previousValue.Visita.Remove(this);
					}
					this._Visitante.Entity = value;
					if ((value != null))
					{
						value.Visita.Add(this);
						this._IdVisitante = value.IdVisitante;
					}
					else
					{
						this._IdVisitante = default(int);
					}
					this.SendPropertyChanged("Visitante");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Secretaria")]
	public partial class Secretaria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSecretaria;
		
		private string _Administracao_e_RH;
		
		private string _Assistencia_Social;
		
		private string _Desenvolvimento_Econômico;
		
		private string _Educação;
		
		private string _Esportes_e_Recreação;
		
		private string _Finanças;
		
		private string _Gabinete_do_Prefeito;
		
		private string _Governo;
		
		private string _Infreaestrutura;
		
		private string _Meio_Ambiente;
		
		private string _Mobilidade_Urbana;
		
		private string _Planejamento;
		
		private string _Procuradoria_Geral;
		
		private string _Saúde;
		
		private string _Segurança_e_Defesa_do_Cidadão;
		
		private string _Fundação_Cultural_de_Jacareí;
		
		private string _Fundação_ProLar;
		
		private string _IPMJ;
		
		private string _SAAE;
		
		private string _SRJ;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSecretariaChanging(int value);
    partial void OnIdSecretariaChanged();
    partial void OnAdministracao_e_RHChanging(string value);
    partial void OnAdministracao_e_RHChanged();
    partial void OnAssistencia_SocialChanging(string value);
    partial void OnAssistencia_SocialChanged();
    partial void OnDesenvolvimento_EconômicoChanging(string value);
    partial void OnDesenvolvimento_EconômicoChanged();
    partial void OnEducaçãoChanging(string value);
    partial void OnEducaçãoChanged();
    partial void OnEsportes_e_RecreaçãoChanging(string value);
    partial void OnEsportes_e_RecreaçãoChanged();
    partial void OnFinançasChanging(string value);
    partial void OnFinançasChanged();
    partial void OnGabinete_do_PrefeitoChanging(string value);
    partial void OnGabinete_do_PrefeitoChanged();
    partial void OnGovernoChanging(string value);
    partial void OnGovernoChanged();
    partial void OnInfreaestruturaChanging(string value);
    partial void OnInfreaestruturaChanged();
    partial void OnMeio_AmbienteChanging(string value);
    partial void OnMeio_AmbienteChanged();
    partial void OnMobilidade_UrbanaChanging(string value);
    partial void OnMobilidade_UrbanaChanged();
    partial void OnPlanejamentoChanging(string value);
    partial void OnPlanejamentoChanged();
    partial void OnProcuradoria_GeralChanging(string value);
    partial void OnProcuradoria_GeralChanged();
    partial void OnSaúdeChanging(string value);
    partial void OnSaúdeChanged();
    partial void OnSegurança_e_Defesa_do_CidadãoChanging(string value);
    partial void OnSegurança_e_Defesa_do_CidadãoChanged();
    partial void OnFundação_Cultural_de_JacareíChanging(string value);
    partial void OnFundação_Cultural_de_JacareíChanged();
    partial void OnFundação_ProLarChanging(string value);
    partial void OnFundação_ProLarChanged();
    partial void OnIPMJChanging(string value);
    partial void OnIPMJChanged();
    partial void OnSAAEChanging(string value);
    partial void OnSAAEChanged();
    partial void OnSRJChanging(string value);
    partial void OnSRJChanged();
    #endregion
		
		public Secretaria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSecretaria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSecretaria
		{
			get
			{
				return this._IdSecretaria;
			}
			set
			{
				if ((this._IdSecretaria != value))
				{
					this.OnIdSecretariaChanging(value);
					this.SendPropertyChanging();
					this._IdSecretaria = value;
					this.SendPropertyChanged("IdSecretaria");
					this.OnIdSecretariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Administracao e RH]", Storage="_Administracao_e_RH", DbType="VarChar(20)")]
		public string Administracao_e_RH
		{
			get
			{
				return this._Administracao_e_RH;
			}
			set
			{
				if ((this._Administracao_e_RH != value))
				{
					this.OnAdministracao_e_RHChanging(value);
					this.SendPropertyChanging();
					this._Administracao_e_RH = value;
					this.SendPropertyChanged("Administracao_e_RH");
					this.OnAdministracao_e_RHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Assistencia Social]", Storage="_Assistencia_Social", DbType="VarChar(20)")]
		public string Assistencia_Social
		{
			get
			{
				return this._Assistencia_Social;
			}
			set
			{
				if ((this._Assistencia_Social != value))
				{
					this.OnAssistencia_SocialChanging(value);
					this.SendPropertyChanging();
					this._Assistencia_Social = value;
					this.SendPropertyChanged("Assistencia_Social");
					this.OnAssistencia_SocialChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Desenvolvimento Econômico]", Storage="_Desenvolvimento_Econômico", DbType="VarChar(20)")]
		public string Desenvolvimento_Econômico
		{
			get
			{
				return this._Desenvolvimento_Econômico;
			}
			set
			{
				if ((this._Desenvolvimento_Econômico != value))
				{
					this.OnDesenvolvimento_EconômicoChanging(value);
					this.SendPropertyChanging();
					this._Desenvolvimento_Econômico = value;
					this.SendPropertyChanged("Desenvolvimento_Econômico");
					this.OnDesenvolvimento_EconômicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Educação", DbType="VarChar(20)")]
		public string Educação
		{
			get
			{
				return this._Educação;
			}
			set
			{
				if ((this._Educação != value))
				{
					this.OnEducaçãoChanging(value);
					this.SendPropertyChanging();
					this._Educação = value;
					this.SendPropertyChanged("Educação");
					this.OnEducaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Esportes e Recreação]", Storage="_Esportes_e_Recreação", DbType="VarChar(20)")]
		public string Esportes_e_Recreação
		{
			get
			{
				return this._Esportes_e_Recreação;
			}
			set
			{
				if ((this._Esportes_e_Recreação != value))
				{
					this.OnEsportes_e_RecreaçãoChanging(value);
					this.SendPropertyChanging();
					this._Esportes_e_Recreação = value;
					this.SendPropertyChanged("Esportes_e_Recreação");
					this.OnEsportes_e_RecreaçãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Finanças", DbType="VarChar(20)")]
		public string Finanças
		{
			get
			{
				return this._Finanças;
			}
			set
			{
				if ((this._Finanças != value))
				{
					this.OnFinançasChanging(value);
					this.SendPropertyChanging();
					this._Finanças = value;
					this.SendPropertyChanged("Finanças");
					this.OnFinançasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Gabinete do Prefeito]", Storage="_Gabinete_do_Prefeito", DbType="VarChar(20)")]
		public string Gabinete_do_Prefeito
		{
			get
			{
				return this._Gabinete_do_Prefeito;
			}
			set
			{
				if ((this._Gabinete_do_Prefeito != value))
				{
					this.OnGabinete_do_PrefeitoChanging(value);
					this.SendPropertyChanging();
					this._Gabinete_do_Prefeito = value;
					this.SendPropertyChanged("Gabinete_do_Prefeito");
					this.OnGabinete_do_PrefeitoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Governo", DbType="VarChar(20)")]
		public string Governo
		{
			get
			{
				return this._Governo;
			}
			set
			{
				if ((this._Governo != value))
				{
					this.OnGovernoChanging(value);
					this.SendPropertyChanging();
					this._Governo = value;
					this.SendPropertyChanged("Governo");
					this.OnGovernoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Infreaestrutura", DbType="VarChar(20)")]
		public string Infreaestrutura
		{
			get
			{
				return this._Infreaestrutura;
			}
			set
			{
				if ((this._Infreaestrutura != value))
				{
					this.OnInfreaestruturaChanging(value);
					this.SendPropertyChanging();
					this._Infreaestrutura = value;
					this.SendPropertyChanged("Infreaestrutura");
					this.OnInfreaestruturaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Meio Ambiente]", Storage="_Meio_Ambiente", DbType="VarChar(20)")]
		public string Meio_Ambiente
		{
			get
			{
				return this._Meio_Ambiente;
			}
			set
			{
				if ((this._Meio_Ambiente != value))
				{
					this.OnMeio_AmbienteChanging(value);
					this.SendPropertyChanging();
					this._Meio_Ambiente = value;
					this.SendPropertyChanged("Meio_Ambiente");
					this.OnMeio_AmbienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mobilidade Urbana]", Storage="_Mobilidade_Urbana", DbType="VarChar(20)")]
		public string Mobilidade_Urbana
		{
			get
			{
				return this._Mobilidade_Urbana;
			}
			set
			{
				if ((this._Mobilidade_Urbana != value))
				{
					this.OnMobilidade_UrbanaChanging(value);
					this.SendPropertyChanging();
					this._Mobilidade_Urbana = value;
					this.SendPropertyChanged("Mobilidade_Urbana");
					this.OnMobilidade_UrbanaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Planejamento", DbType="VarChar(20)")]
		public string Planejamento
		{
			get
			{
				return this._Planejamento;
			}
			set
			{
				if ((this._Planejamento != value))
				{
					this.OnPlanejamentoChanging(value);
					this.SendPropertyChanging();
					this._Planejamento = value;
					this.SendPropertyChanged("Planejamento");
					this.OnPlanejamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Procuradoria Geral]", Storage="_Procuradoria_Geral", DbType="VarChar(20)")]
		public string Procuradoria_Geral
		{
			get
			{
				return this._Procuradoria_Geral;
			}
			set
			{
				if ((this._Procuradoria_Geral != value))
				{
					this.OnProcuradoria_GeralChanging(value);
					this.SendPropertyChanging();
					this._Procuradoria_Geral = value;
					this.SendPropertyChanged("Procuradoria_Geral");
					this.OnProcuradoria_GeralChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Saúde", DbType="VarChar(20)")]
		public string Saúde
		{
			get
			{
				return this._Saúde;
			}
			set
			{
				if ((this._Saúde != value))
				{
					this.OnSaúdeChanging(value);
					this.SendPropertyChanging();
					this._Saúde = value;
					this.SendPropertyChanged("Saúde");
					this.OnSaúdeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Segurança e Defesa do Cidadão]", Storage="_Segurança_e_Defesa_do_Cidadão", DbType="VarChar(20)")]
		public string Segurança_e_Defesa_do_Cidadão
		{
			get
			{
				return this._Segurança_e_Defesa_do_Cidadão;
			}
			set
			{
				if ((this._Segurança_e_Defesa_do_Cidadão != value))
				{
					this.OnSegurança_e_Defesa_do_CidadãoChanging(value);
					this.SendPropertyChanging();
					this._Segurança_e_Defesa_do_Cidadão = value;
					this.SendPropertyChanged("Segurança_e_Defesa_do_Cidadão");
					this.OnSegurança_e_Defesa_do_CidadãoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fundação Cultural de Jacareí]", Storage="_Fundação_Cultural_de_Jacareí", DbType="VarChar(20)")]
		public string Fundação_Cultural_de_Jacareí
		{
			get
			{
				return this._Fundação_Cultural_de_Jacareí;
			}
			set
			{
				if ((this._Fundação_Cultural_de_Jacareí != value))
				{
					this.OnFundação_Cultural_de_JacareíChanging(value);
					this.SendPropertyChanging();
					this._Fundação_Cultural_de_Jacareí = value;
					this.SendPropertyChanged("Fundação_Cultural_de_Jacareí");
					this.OnFundação_Cultural_de_JacareíChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fundação ProLar]", Storage="_Fundação_ProLar", DbType="VarChar(20)")]
		public string Fundação_ProLar
		{
			get
			{
				return this._Fundação_ProLar;
			}
			set
			{
				if ((this._Fundação_ProLar != value))
				{
					this.OnFundação_ProLarChanging(value);
					this.SendPropertyChanging();
					this._Fundação_ProLar = value;
					this.SendPropertyChanged("Fundação_ProLar");
					this.OnFundação_ProLarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPMJ", DbType="VarChar(20)")]
		public string IPMJ
		{
			get
			{
				return this._IPMJ;
			}
			set
			{
				if ((this._IPMJ != value))
				{
					this.OnIPMJChanging(value);
					this.SendPropertyChanging();
					this._IPMJ = value;
					this.SendPropertyChanged("IPMJ");
					this.OnIPMJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAAE", DbType="VarChar(20)")]
		public string SAAE
		{
			get
			{
				return this._SAAE;
			}
			set
			{
				if ((this._SAAE != value))
				{
					this.OnSAAEChanging(value);
					this.SendPropertyChanging();
					this._SAAE = value;
					this.SendPropertyChanged("SAAE");
					this.OnSAAEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SRJ", DbType="VarChar(20)")]
		public string SRJ
		{
			get
			{
				return this._SRJ;
			}
			set
			{
				if ((this._SRJ != value))
				{
					this.OnSRJChanging(value);
					this.SendPropertyChanging();
					this._SRJ = value;
					this.SendPropertyChanged("SRJ");
					this.OnSRJChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
