#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecepcaoDados
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RecepcaoSistema")]
	public partial class RecepcaoDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFuncionario(Funcionario instance);
    partial void UpdateFuncionario(Funcionario instance);
    partial void DeleteFuncionario(Funcionario instance);
    partial void InsertVisitante(Visitante instance);
    partial void UpdateVisitante(Visitante instance);
    partial void DeleteVisitante(Visitante instance);
    partial void InsertVisita(Visita instance);
    partial void UpdateVisita(Visita instance);
    partial void DeleteVisita(Visita instance);
    #endregion
		
		public RecepcaoDataClassesDataContext() : 
				base(global::RecepcaoDados.Properties.Settings.Default.RecepcaoSistemaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RecepcaoDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Funcionario> Funcionario
		{
			get
			{
				return this.GetTable<Funcionario>();
			}
		}
		
		public System.Data.Linq.Table<Visitante> Visitante
		{
			get
			{
				return this.GetTable<Visitante>();
			}
		}
		
		public System.Data.Linq.Table<Visita> Visita
		{
			get
			{
				return this.GetTable<Visita>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Funcionario")]
	public partial class Funcionario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdFuncionario;
		
		private string _Nome;
		
		private string _Login;
		
		private string _Senha;
		
		private string _Perfil;
		
		private EntitySet<Visita> _Visita;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdFuncionarioChanging(int value);
    partial void OnIdFuncionarioChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnSenhaChanging(string value);
    partial void OnSenhaChanged();
    partial void OnPerfilChanging(string value);
    partial void OnPerfilChanged();
    #endregion
		
		public Funcionario()
		{
			this._Visita = new EntitySet<Visita>(new Action<Visita>(this.attach_Visita), new Action<Visita>(this.detach_Visita));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFuncionario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdFuncionario
		{
			get
			{
				return this._IdFuncionario;
			}
			set
			{
				if ((this._IdFuncionario != value))
				{
					this.OnIdFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._IdFuncionario = value;
					this.SendPropertyChanged("IdFuncionario");
					this.OnIdFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Senha", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Senha
		{
			get
			{
				return this._Senha;
			}
			set
			{
				if ((this._Senha != value))
				{
					this.OnSenhaChanging(value);
					this.SendPropertyChanging();
					this._Senha = value;
					this.SendPropertyChanged("Senha");
					this.OnSenhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Perfil", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Perfil
		{
			get
			{
				return this._Perfil;
			}
			set
			{
				if ((this._Perfil != value))
				{
					this.OnPerfilChanging(value);
					this.SendPropertyChanging();
					this._Perfil = value;
					this.SendPropertyChanged("Perfil");
					this.OnPerfilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcionario_Visita", Storage="_Visita", ThisKey="IdFuncionario", OtherKey="IdFuncionario")]
		public EntitySet<Visita> Visita
		{
			get
			{
				return this._Visita;
			}
			set
			{
				this._Visita.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Funcionario = this;
		}
		
		private void detach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Funcionario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visitante")]
	public partial class Visitante : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVisitante;
		
		private string _CPF;
		
		private string _RG;
		
		private string _RNE;
		
		private string _Nome;
		
		private System.Nullable<bool> _Estrangeiro;
		
		private System.Nullable<byte> _Idade;
		
		private string _Logradouro;
		
		private string _Bairro;
		
		private string _Cidade;
		
		private string _UF;
		
		private string _Pais;
		
		private string _Foto;
		
		private EntitySet<Visita> _Visita;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVisitanteChanging(int value);
    partial void OnIdVisitanteChanged();
    partial void OnCPFChanging(string value);
    partial void OnCPFChanged();
    partial void OnRGChanging(string value);
    partial void OnRGChanged();
    partial void OnRNEChanging(string value);
    partial void OnRNEChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnEstrangeiroChanging(System.Nullable<bool> value);
    partial void OnEstrangeiroChanged();
    partial void OnIdadeChanging(System.Nullable<byte> value);
    partial void OnIdadeChanged();
    partial void OnLogradouroChanging(string value);
    partial void OnLogradouroChanged();
    partial void OnBairroChanging(string value);
    partial void OnBairroChanged();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnUFChanging(string value);
    partial void OnUFChanged();
    partial void OnPaisChanging(string value);
    partial void OnPaisChanged();
    partial void OnFotoChanging(string value);
    partial void OnFotoChanged();
    #endregion
		
		public Visitante()
		{
			this._Visita = new EntitySet<Visita>(new Action<Visita>(this.attach_Visita), new Action<Visita>(this.detach_Visita));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVisitante", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVisitante
		{
			get
			{
				return this._IdVisitante;
			}
			set
			{
				if ((this._IdVisitante != value))
				{
					this.OnIdVisitanteChanging(value);
					this.SendPropertyChanging();
					this._IdVisitante = value;
					this.SendPropertyChanged("IdVisitante");
					this.OnIdVisitanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPF", DbType="VarChar(15)")]
		public string CPF
		{
			get
			{
				return this._CPF;
			}
			set
			{
				if ((this._CPF != value))
				{
					this.OnCPFChanging(value);
					this.SendPropertyChanging();
					this._CPF = value;
					this.SendPropertyChanged("CPF");
					this.OnCPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RG", DbType="VarChar(15)")]
		public string RG
		{
			get
			{
				return this._RG;
			}
			set
			{
				if ((this._RG != value))
				{
					this.OnRGChanging(value);
					this.SendPropertyChanging();
					this._RG = value;
					this.SendPropertyChanged("RG");
					this.OnRGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RNE", DbType="VarChar(15)")]
		public string RNE
		{
			get
			{
				return this._RNE;
			}
			set
			{
				if ((this._RNE != value))
				{
					this.OnRNEChanging(value);
					this.SendPropertyChanging();
					this._RNE = value;
					this.SendPropertyChanged("RNE");
					this.OnRNEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estrangeiro", DbType="Bit")]
		public System.Nullable<bool> Estrangeiro
		{
			get
			{
				return this._Estrangeiro;
			}
			set
			{
				if ((this._Estrangeiro != value))
				{
					this.OnEstrangeiroChanging(value);
					this.SendPropertyChanging();
					this._Estrangeiro = value;
					this.SendPropertyChanged("Estrangeiro");
					this.OnEstrangeiroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Idade", DbType="TinyInt")]
		public System.Nullable<byte> Idade
		{
			get
			{
				return this._Idade;
			}
			set
			{
				if ((this._Idade != value))
				{
					this.OnIdadeChanging(value);
					this.SendPropertyChanging();
					this._Idade = value;
					this.SendPropertyChanged("Idade");
					this.OnIdadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logradouro", DbType="VarChar(50)")]
		public string Logradouro
		{
			get
			{
				return this._Logradouro;
			}
			set
			{
				if ((this._Logradouro != value))
				{
					this.OnLogradouroChanging(value);
					this.SendPropertyChanging();
					this._Logradouro = value;
					this.SendPropertyChanged("Logradouro");
					this.OnLogradouroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bairro", DbType="VarChar(50)")]
		public string Bairro
		{
			get
			{
				return this._Bairro;
			}
			set
			{
				if ((this._Bairro != value))
				{
					this.OnBairroChanging(value);
					this.SendPropertyChanging();
					this._Bairro = value;
					this.SendPropertyChanged("Bairro");
					this.OnBairroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="VarChar(50)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="VarChar(2)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this.OnUFChanging(value);
					this.SendPropertyChanging();
					this._UF = value;
					this.SendPropertyChanged("UF");
					this.OnUFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pais", DbType="VarChar(50)")]
		public string Pais
		{
			get
			{
				return this._Pais;
			}
			set
			{
				if ((this._Pais != value))
				{
					this.OnPaisChanging(value);
					this.SendPropertyChanging();
					this._Pais = value;
					this.SendPropertyChanged("Pais");
					this.OnPaisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarChar(50)")]
		public string Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visitante_Visita", Storage="_Visita", ThisKey="IdVisitante", OtherKey="IdVisitante")]
		public EntitySet<Visita> Visita
		{
			get
			{
				return this._Visita;
			}
			set
			{
				this._Visita.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Visitante = this;
		}
		
		private void detach_Visita(Visita entity)
		{
			this.SendPropertyChanging();
			entity.Visitante = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Visita")]
	public partial class Visita : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdVisita;
		
		private int _IdVisitante;
		
		private int _IdFuncionario;
		
		private string _Secretaria;
		
		private string _Setor;
		
		private string _ContatoInterno;
		
		private bool _Liberacao;
		
		private System.DateTime _Data;
		
		private EntityRef<Funcionario> _Funcionario;
		
		private EntityRef<Visitante> _Visitante;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdVisitaChanging(int value);
    partial void OnIdVisitaChanged();
    partial void OnIdVisitanteChanging(int value);
    partial void OnIdVisitanteChanged();
    partial void OnIdFuncionarioChanging(int value);
    partial void OnIdFuncionarioChanged();
    partial void OnSecretariaChanging(string value);
    partial void OnSecretariaChanged();
    partial void OnSetorChanging(string value);
    partial void OnSetorChanged();
    partial void OnContatoInternoChanging(string value);
    partial void OnContatoInternoChanged();
    partial void OnLiberacaoChanging(bool value);
    partial void OnLiberacaoChanged();
    partial void OnDataChanging(System.DateTime value);
    partial void OnDataChanged();
    #endregion
		
		public Visita()
		{
			this._Funcionario = default(EntityRef<Funcionario>);
			this._Visitante = default(EntityRef<Visitante>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVisita", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdVisita
		{
			get
			{
				return this._IdVisita;
			}
			set
			{
				if ((this._IdVisita != value))
				{
					this.OnIdVisitaChanging(value);
					this.SendPropertyChanging();
					this._IdVisita = value;
					this.SendPropertyChanged("IdVisita");
					this.OnIdVisitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdVisitante", DbType="Int NOT NULL")]
		public int IdVisitante
		{
			get
			{
				return this._IdVisitante;
			}
			set
			{
				if ((this._IdVisitante != value))
				{
					if (this._Visitante.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdVisitanteChanging(value);
					this.SendPropertyChanging();
					this._IdVisitante = value;
					this.SendPropertyChanged("IdVisitante");
					this.OnIdVisitanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdFuncionario", DbType="Int NOT NULL")]
		public int IdFuncionario
		{
			get
			{
				return this._IdFuncionario;
			}
			set
			{
				if ((this._IdFuncionario != value))
				{
					if (this._Funcionario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdFuncionarioChanging(value);
					this.SendPropertyChanging();
					this._IdFuncionario = value;
					this.SendPropertyChanged("IdFuncionario");
					this.OnIdFuncionarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Secretaria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Secretaria
		{
			get
			{
				return this._Secretaria;
			}
			set
			{
				if ((this._Secretaria != value))
				{
					this.OnSecretariaChanging(value);
					this.SendPropertyChanging();
					this._Secretaria = value;
					this.SendPropertyChanged("Secretaria");
					this.OnSecretariaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setor", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Setor
		{
			get
			{
				return this._Setor;
			}
			set
			{
				if ((this._Setor != value))
				{
					this.OnSetorChanging(value);
					this.SendPropertyChanging();
					this._Setor = value;
					this.SendPropertyChanged("Setor");
					this.OnSetorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContatoInterno", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ContatoInterno
		{
			get
			{
				return this._ContatoInterno;
			}
			set
			{
				if ((this._ContatoInterno != value))
				{
					this.OnContatoInternoChanging(value);
					this.SendPropertyChanging();
					this._ContatoInterno = value;
					this.SendPropertyChanged("ContatoInterno");
					this.OnContatoInternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Liberacao", DbType="Bit NOT NULL")]
		public bool Liberacao
		{
			get
			{
				return this._Liberacao;
			}
			set
			{
				if ((this._Liberacao != value))
				{
					this.OnLiberacaoChanging(value);
					this.SendPropertyChanging();
					this._Liberacao = value;
					this.SendPropertyChanged("Liberacao");
					this.OnLiberacaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data", DbType="SmallDateTime NOT NULL")]
		public System.DateTime Data
		{
			get
			{
				return this._Data;
			}
			set
			{
				if ((this._Data != value))
				{
					this.OnDataChanging(value);
					this.SendPropertyChanging();
					this._Data = value;
					this.SendPropertyChanged("Data");
					this.OnDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Funcionario_Visita", Storage="_Funcionario", ThisKey="IdFuncionario", OtherKey="IdFuncionario", IsForeignKey=true)]
		public Funcionario Funcionario
		{
			get
			{
				return this._Funcionario.Entity;
			}
			set
			{
				Funcionario previousValue = this._Funcionario.Entity;
				if (((previousValue != value) 
							|| (this._Funcionario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Funcionario.Entity = null;
						previousValue.Visita.Remove(this);
					}
					this._Funcionario.Entity = value;
					if ((value != null))
					{
						value.Visita.Add(this);
						this._IdFuncionario = value.IdFuncionario;
					}
					else
					{
						this._IdFuncionario = default(int);
					}
					this.SendPropertyChanged("Funcionario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Visitante_Visita", Storage="_Visitante", ThisKey="IdVisitante", OtherKey="IdVisitante", IsForeignKey=true)]
		public Visitante Visitante
		{
			get
			{
				return this._Visitante.Entity;
			}
			set
			{
				Visitante previousValue = this._Visitante.Entity;
				if (((previousValue != value) 
							|| (this._Visitante.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Visitante.Entity = null;
						previousValue.Visita.Remove(this);
					}
					this._Visitante.Entity = value;
					if ((value != null))
					{
						value.Visita.Add(this);
						this._IdVisitante = value.IdVisitante;
					}
					else
					{
						this._IdVisitante = default(int);
					}
					this.SendPropertyChanged("Visitante");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
